name: Trigger Launch deployment on content change

on:
  push:
    tags:
      - 'content/*'  # Triggers on any tag starting with "hotfix/"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with hotfix tag
        run: |
          echo "${{ github.sha }}"
          echo "${{ steps.get_sha.outputs.SHA }}"
          curl -X POST https://launch-api.contentstack.com/manage/deploy/6696433097d0365831e67186?commit=${{ github.sha }}
          
