name: Trigger Launch deployment on content change

on:
  push:
    tags:
      - 'content/*'  # Triggers on any tag starting with "content/"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with content tag
        run: curl -X POST https://<your-deploy-hook-url>?commit=${{ github.sha }}
          
